.\" Copyright (c) 2019 {{cookiecutter.full_name}} <{{cookiecutter.email}}>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd May 29, 2019
.Dt {{cookiecutter.project_name|upper}} 4
.Os
.Sh NAME
.Nm {{cookiecutter.project_name}}
.Nd {{cookiecutter.project_description}}
.\" TODO: A manual page will help your users to find how to use
.\" TODO: your program. Keep it up-to-date.
.\" TODO: Have a look at this URL for more information about the
.\" TODO: markup language used:
.\" TODO:  http://www.openbsd.org/cgi-bin/man.cgi?query=mdoc&sektion=7
.Sh SYNOPSIS
.Nm /etc/{{cookiecutter.project_name}}
.Sh DESCRIPTION
{{cookiecutter.project_description}}
.El
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An {{cookiecutter.full_name}} Aq {{cookiecutter.email}} .
